using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.Localization;
using UnityEngine.Localization.Settings;

namespace WildfrostAccessibility
{
    /// <summary>
    /// The German half of the screen handler string table (Town, ContinueRun,
    /// Map, Battle and the shared item descriptions).
    /// </summary>
    public static partial class Loc
    {
        private static void RegisterHandlerStringsGerman()
        {
            // ----- German -------------------------------------------------------

            Add("de", "stat_health", "{0} Leben");
            Add("de", "stat_health_of_max", "{0} von {1} Leben");
            Add("de", "stat_attack", "{0} Angriff");
            Add("de", "stat_counter", "Zaehler {0}");
            Add("de", "pocket_draw", "Nachziehstapel, {0} Karten");
            Add("de", "pocket_draw_one", "Nachziehstapel, 1 Karte");
            Add("de", "pocket_discard", "Ablagestapel, {0} Karten");
            Add("de", "pocket_discard_one", "Ablagestapel, 1 Karte");
            Add("de", "card_count_multiple", "{0}, {1} mal");
            Add("de", "no_item_focused", "Nichts fokussiert.");
            Add("de", "no_info_available", "Keine Informationen verfuegbar.");
            Add("de", "gold_amount", "Gold: {0}.");
            Add("de", "shop_price", "Kostet {0} Gold.");
            Add("de", "shop_price_afford", "Kostet {0} Gold. Du hast {1}.");
            Add("de", "shop_price_cant_afford", "Kostet {0} Gold. Du kannst es dir nicht leisten; du hast {1}.");
            Add("de", "scene_CharacterSelect", "Charakterauswahl.");
            Add("de", "scene_Cards", "Kartensammlung.");
            Add("de", "scene_Mods", "Mods.");
            Add("de", "scene_Credits", "Mitwirkende.");
            Add("de", "scene_TownUnlocks", "Stadt-Freischaltungen.");
            Add("de", "scene_Event", "Ereignis.");
            Add("de", "scene_BossReward", "Boss-Belohnung.");
            Add("de", "scene_BattleWin", "Kampf gewonnen! Siegesbildschirm.");
            Add("de", "scene_CampaignEnd", "Reise beendet.");
            Add("de", "campaignend_win", "Sieg!");
            Add("de", "campaignend_defeat", "Besiegt.");
            Add("de", "campaignend_vanquished", "Bezwungen!");
            Add("de", "campaignend_time", "Zeit");
            Add("de", "campaignend_battles", "Gewonnene Kaempfe");
            Add("de", "campaignend_blings", "Blings");
            Add("de", "campaignend_score", "Deine Punktzahl: {0}.");
            Add("de", "campaignend_town_progress", "Stadtfortschritt: {0}.");
            Add("de", "help_campaignend", "Zusammenfassung am Ende einer Reise: Ergebnis, Laufstatistiken, Stadtfortschritt und Endpunktzahl. Pfeiltasten erreichen Zurueck zur Stadt und Punkte, Enter waehlt. Strg+Hoch wiederholt die Zusammenfassung.");
            Add("de", "battlewin_continue", "Druecke Enter, um fortzufahren.");
            Add("de", "battlewin_injuries", "In diesem Kampf verletzt: {0}.");
            Add("de", "battlewin_not_ready", "Der Siegesbildschirm erscheint noch, einen Moment.");
            Add("de", "help_battlewin", "Siegesbildschirm nach einem gewonnenen Kampf. Zeigt gegebenenfalls im Kampf verletzte Gefaehrten. Enter setzt die Reise fort.");
            Add("de", "charselect_leaders", "Waehle deinen Anfuehrer. Pfeiltasten wechseln zwischen den Anfuehrern, Enter waehlt aus.");
            Add("de", "charselect_chosen", "{0} gewaehlt. Enter bestaetigt, Escape legt die Karte zurueck.");
            Add("de", "charselect_chosen_generic", "Karte gewaehlt. Enter bestaetigt, Escape legt sie zurueck.");
            Add("de", "charselect_cancelled", "Auswahl abgebrochen, zurueck zur Uebersicht.");
            Add("de", "charselect_pets", "Waehle dein Start-Haustier. Pfeiltasten wechseln, Enter waehlt aus.");
            Add("de", "charselect_starting", "Los geht's! Die Reise beginnt.");
            Add("de", "tribe_locked", "{0}, gesperrt");
            Add("de", "tribe_locked_hint", "Neue Staemme werden freigeschaltet, waehrend sich die Fortschrittsanzeige der Stadt fuellt: gewinne weiter Kaempfe und beende Laeufe.");
            Add("de", "tribe_locked_building", "Die Freischaltung erscheint beim {0}.");
            Add("de", "tribe_locked_blocked", "{0} ist gesperrt und kann nicht gewaehlt werden. {1}");
            Add("de", "charselect_tribes_locked", "Noch nicht freigeschaltete Staemme werden weiterhin angezeigt: sie werden als gesperrt vorgelesen und koennen nicht gewaehlt werden.");
            Add("de", "inspect_no_confirm", "Dieses Fenster kann hier nicht bestaetigt werden. Escape legt die Karte zurueck.");
            Add("de", "help_charselect", "Charakterauswahl in drei Schritten. Zuerst ein Stamm: Pfeiltasten hoch und runter wechseln zwischen den Staemmen und lesen Name und Spielstil vor, die Pfeiltaste rechts liest Anfuehrer und Startdeck des Stammes, und Strg plus hoch geht sie im Lesepuffer durch. Enter waehlt den fokussierten Stamm. Danach ein Anfuehrer und ein Start-Haustier, mit den Pfeiltasten durchgesehen, Enter waehlt aus. Nach dem Auswaehlen einer Karte bestaetigt Enter und setzt fort, Escape legt sie zurueck. I untersucht die fokussierte Karte.");
            Add("de", "help_main_menu", "Hauptmenue. Pfeiltasten hoch und runter wechseln die Knoepfe, Enter waehlt aus. F1 wiederholt diese Hilfe, F10 schaltet den Debug-Modus um.");
            Add("de", "screen_town", "Stadt, dein Lager.");
            Add("de", "town_hint", "Pfeiltasten wechseln zwischen Gebaeuden, Enter waehlt aus, I beschreibt das fokussierte Gebaeude. F1 fuer Hilfe.");
            Add("de", "gate_continue_tutorial", "Deine Tutorial-Reise laeuft. Enter setzt sie fort");
            Add("de", "gate_start_tutorial", "Startet deine erste Reise. Das Spiel bietet dir das Tutorial an");
            Add("de", "gate_continue_run", "Deine Reise laeuft. Enter setzt sie fort");
            Add("de", "gate_start_run", "Startet eine neue Reise");

            // Daily Voyage balloon
            Add("de", "balloon_start_run", "Startet die taegliche Reise: ein festes Deck und Modifikatoren, gewertet in der Bestenliste. Enter oeffnet die heutige Reise");
            Add("de", "balloon_continue_run", "Deine taegliche Reise laeuft. Enter setzt sie fort");
            Add("de", "balloon_deck", "Festes Deck mit {0} Karten: {1}");
            Add("de", "balloon_modifiers", "{0} Modifikatoren: {1}");
            Add("de", "balloon_loading", "Taegliche Reise. Heutige Reise wird geladen.");
            Add("de", "balloon_play_desc", "Startet die heutige taegliche Reise");
            Add("de", "balloon_scores_desc", "Oeffnet die Bestenliste der heutigen Reise");
            Add("de", "balloon_buttons_hint", "Links und rechts wechseln zwischen Los geht's und Bestenliste, Enter waehlt, I liest erneut vor, Escape verlaesst");
            Add("de", "help_town", "Stadt. Dein Lager zwischen den Reisen. Gebaeude schalten neue Karten und Herausforderungen frei. Pfeiltasten wechseln zwischen Gebaeuden, I liest die Funktion vor, Enter oeffnet. Das Tor startet deine Reise oder setzt sie fort.");
            Add("de", "screen_continue_run", "Reise fortsetzen. Du hast eine laufende Reise.");
            Add("de", "continue_missing_data", "Diese Reise nutzt fehlende Inhalte und kann nicht fortgesetzt werden.");
            Add("de", "continue_started", "Gestartet am {0}.");
            Add("de", "continue_leader", "Dein Anfuehrer: {0}.");
            Add("de", "continue_deck", "Deck mit {0} Karten: {1}.");
            Add("de", "continue_hint", "Pfeiltasten gehen durch Karten und Knoepfe. Enter auf Los geht's setzt die Reise fort.");
            Add("de", "continue_button_desc", "Setzt deine Reise fort");
            Add("de", "continue_back_desc", "Zurueck zur Stadt");
            Add("de", "help_continue_run", "Reise-fortsetzen-Bildschirm. Zeigt die laufende Reise: Anfuehrer, Deck und Startdatum. Enter auf dem Fortsetzen-Knopf setzt die Reise fort. Der Zurueck-Knopf fuehrt zur Stadt. Aufgeben verwirft die Reise.");
            Add("de", "screen_map", "Reisekarte.");
            Add("de", "map_zone", "Zone: {0}.");
            Add("de", "map_you_are_at", "Du bist bei {0}.");
            Add("de", "map_destinations", "{0} Ziele: {1}.");
            Add("de", "map_hint", "Pfeiltasten links und rechts bewegen sich auf dem Pfad, Enter reist. M liest die ganze Karte, I liest Details, G liest Gold, P oeffnet das Inventar.");
            Add("de", "map_node_here", "du bist hier");
            Add("de", "map_node_enter", "Enter betritt den Ort");
            Add("de", "map_only_location", "Das ist gerade der einzige aufgedeckte Ort.");
            Add("de", "map_no_controls", "Sonst nichts auf diesem Bildschirm.");
            Add("de", "map_node_cleared", "abgeschlossen");
            Add("de", "map_node_available", "verfuegbar, Enter reist hierher");
            Add("de", "map_node_available_short", "verfuegbar");
            Add("de", "map_node_ahead", "weiter voraus");
            Add("de", "map_node_not_reachable", "nicht erreichbar");
            Add("de", "map_battle_waves", "{0} Wellen");
            Add("de", "map_not_ready", "Die Karte ist noch nicht bereit.");
            Add("de", "map_overview", "Kartenuebersicht, {0} bekannte Orte.");
            Add("de", "map_hidden_nodes", "{0} weitere Orte noch nicht aufgedeckt");
            Add("de", "map_wave_enemies", "Welle {0}: {1}");
            Add("de", "map_fork_here", "Der Pfad teilt sich hier und die Zweige treffen nie wieder aufeinander: eine Wahl gibt die anderen auf.");
            Add("de", "map_fork_rejoins", "die Wege treffen wieder zusammen, es geht nichts verloren");
            Add("de", "map_fork_gives_up", "das gibt auf: {0}");
            Add("de", "map_fork_gives_up_more", "das gibt auf: {0}, und {1} weitere");
            Add("de", "map_fork_gives_up_unseen", "das gibt {0} Orte weiter hinten im anderen Zweig auf");
            Add("de", "help_map", "Reisekarte. Deine Reise ist ein Pfad aus Orten. Pfeiltasten links und rechts wechseln zwischen Orten. Enter reist zu einem verfuegbaren Ort. Hoch und runter erreichen Kartenstapel und weitere Elemente. M liest die ganze Karte, I liest Details samt Gegnern, G liest dein Gold. P oeffnet dein Inventar mit Deck und Talismanen.");

            // Inventar-Overlay (Deckpack): Deck, Reserve, Talismane, Kronen
            Add("de", "deckpack_unavailable", "Kein Inventar auf diesem Bildschirm.");
            Add("de", "deckpack_blocked", "Das Inventar kann gerade nicht geoeffnet werden.");
            Add("de", "deckpack_open", "Inventar geoeffnet.");
            Add("de", "deckpack_closed", "Inventar geschlossen.");
            Add("de", "deckpack_part_deck", "{0} im Deck");
            Add("de", "deckpack_part_reserve", "{0} in der Reserve");
            Add("de", "deckpack_part_charms", "{0} Talismane");
            Add("de", "deckpack_part_charm_one", "1 Talisman");
            Add("de", "deckpack_part_crowns", "{0} Kronen");
            Add("de", "deckpack_part_crown_one", "1 Krone");
            Add("de", "deckpack_hint", "Hoch und runter wechseln die Gruppen, links und rechts bewegen sich innerhalb. Enter auf einem Talisman nimmt ihn auf, Enter auf einer Karte oeffnet ihre Optionen. P oder Escape schliesst. F1 fuer die volle Hilfe.");
            Add("de", "deckpack_group_deck", "Deck, {0} Karten");
            Add("de", "deckpack_group_deck_one", "Deck, 1 Karte");
            Add("de", "deckpack_group_reserve", "Reserve, {0} Karten");
            Add("de", "deckpack_group_reserve_one", "Reserve, 1 Karte");
            Add("de", "deckpack_group_charms", "Talismane, {0}");
            Add("de", "deckpack_group_crowns", "Kronen, {0}");
            Add("de", "deckpack_group_controls", "Schaltflaechen");
            Add("de", "deckpack_pickup", "{0} aufgenommen. {1} Karten koennen ihn tragen. Pfeiltasten wechseln zwischen ihnen, Enter befestigt dauerhaft, Escape legt zurueck.");
            Add("de", "deckpack_pickup_one", "{0} aufgenommen. Eine Karte kann ihn tragen. Enter befestigt dauerhaft, Escape legt zurueck.");
            Add("de", "deckpack_pickup_none", "{0}: keine Karte kann das gerade tragen. Zurueckgelegt.");
            Add("de", "deckpack_battle_blocked", "Talismane koennen im Kampf nicht angebracht werden.");
            Add("de", "deckpack_returned", "{0} zurueckgelegt.");
            Add("de", "deckpack_applying", "{0} wird an {1} angebracht.");
            Add("de", "deckpack_applied", "{0} angebracht.");
            Add("de", "deckpack_not_eligible", "Diese Karte kann {0} nicht tragen.");
            Add("de", "deckpack_target_slots", "{0} von {1} Talisman-Plaetzen belegt");
            Add("de", "charm_gained", "Talisman erhalten! {0}");
            Add("de", "charm_gained_hint", "Enter bringt ihn jetzt an einer Karte an, Escape bewahrt ihn fuer spaeter im Inventar auf.");
            Add("de", "charm_reserved", "{0} im Inventar aufbewahrt. Mit P jederzeit anbringbar.");
            Add("de", "charm_assign_button", "{0} Enter bringt diesen Talisman jetzt an einer Karte an, Escape bewahrt ihn fuer spaeter im Inventar auf.");
            Add("de", "deckpack_menu_open", "Optionen fuer {0}: {1}. Links und rechts waehlen, Enter aktiviert, Escape schliesst.");
            Add("de", "deckpack_menu_closed", "Optionen geschlossen.");
            Add("de", "deckpack_option_rename", "Umbenennen");
            Add("de", "deckpack_option_take_crown", "Krone abnehmen");
            Add("de", "deckpack_option_move_reserve", "In die Reserve");
            Add("de", "deckpack_option_move_deck", "Ins Deck");
            Add("de", "deckpack_moved_reserve", "{0} in die Reserve verschoben.");
            Add("de", "deckpack_moved_deck", "{0} ins Deck verschoben.");
            Add("de", "deckpack_crown_taken", "Krone von {0} abgenommen und ins Inventar gelegt.");
            Add("de", "deckpack_card_blocked", "Kartenoptionen sind gerade nicht verfuegbar.");
            Add("de", "help_deckpack", "Inventar. Dein Deck, Reservekarten und gesammelte Talismane und Kronen. Hoch und runter wechseln die Gruppen: Deck, Reserve, Talismane, Kronen und Schaltflaechen. Links und rechts bewegen sich innerhalb einer Gruppe. Enter auf einem Talisman oder einer Krone nimmt sie auf: Pfeiltasten wechseln dann zwischen den Karten, die sie tragen koennen, Enter befestigt dauerhaft, Escape legt zurueck. Enter auf einer Karte oeffnet ihre Optionen, etwa zwischen Deck und Reserve verschieben. I untersucht die fokussierte Karte. P oder Escape schliesst das Inventar.");
            Add("de", "node_type_boss", "Bosskampf");
            Add("de", "node_type_battle", "Kampf");
            Add("de", "node_type_shop", "Laden");
            Add("de", "node_type_gnomeshop", "Gnomladen");
            Add("de", "node_type_charm", "Talisman-Ereignis");
            Add("de", "node_type_gold", "Schatz");
            Add("de", "node_type_item", "Gegenstand-Ereignis");
            Add("de", "node_type_companion", "Gefaehrten-Ereignis");
            Add("de", "node_type_copyitem", "Gegenstand-Kopier-Ereignis");
            Add("de", "node_type_curseitems", "Fluch-Ereignis");
            Add("de", "node_type_injuredcompanion", "verletzter Gefaehrte");
            Add("de", "node_type_journalpage", "Journalseite");
            Add("de", "node_type_charmshop", "Talisman-Laden");
            Add("de", "node_type_clunkshop", "Klunker-Laden");
            Add("de", "node_type_muncher", "Muncher");
            Add("de", "node_type_event", "Ereignis");
            Add("de", "screen_battle", "Kampf!");
            Add("de", "battle_wave_total", "{0} Gegnerwellen.");
            Add("de", "battle_hand_count", "{0} Karten auf der Hand.");
            Add("de", "battle_hint", "Hoch und runter wechseln zwischen Hand, Feldern, Glocke und Stapeln. Links und rechts bewegen sich innerhalb. Enter nimmt Karten auf und legt sie ab. F1 fuer Kampfhilfe.");
            Add("de", "battle_your_turn", "Dein Zug. {0} Karten auf der Hand.");
            Add("de", "battle_resolving", "Zug wird ausgefuehrt.");
            Add("de", "battle_over", "Kampf vorbei.");
            Add("de", "battle_turn", "Runde {0}.");
            Add("de", "battle_bell_rung", "Nachziehglocke gelaeutet. Neue Hand wird gezogen.");
            Add("de", "battle_group_empty", "{0} ist leer.");
            Add("de", "battle_nothing_to_focus", "Nichts zu fokussieren.");
            Add("de", "group_hand", "Hand");
            Add("de", "group_your_board", "Dein Feld");
            Add("de", "group_enemy_board", "Gegnerfeld");
            Add("de", "group_system", "Glocke und Stapel");
            Add("de", "battle_card_picked_up", "{0} aufgenommen.");
            Add("de", "battle_pickup_hint", "Pfeiltasten waehlen ein Ziel, Enter legt ab.");
            Add("de", "battle_card_released", "{0} abgelegt.");
            Add("de", "battle_invalid_target", "Kein gueltiges Ziel.");
            Add("de", "battle_cannot_play", "Diese Karte kann gerade nicht gespielt werden.");
            Add("de", "battle_bell_not_ready", "Die Nachziehglocke ist gerade nicht verfuegbar.");
            Add("de", "battle_hand_empty", "Deine Hand ist leer.");
            Add("de", "battle_acts_in", "handelt in {0}");
            Add("de", "battle_use_on_hand", "Ohne Ziel spielen");
            Add("de", "battle_no_waves", "Keine Welleninformationen.");
            Add("de", "battle_wave_n", "Welle {0}: {1}");
            Add("de", "battle_boss_wave", "Bosswelle");
            Add("de", "battle_all_waves_spawned", "Alle Wellen sind erschienen.");
            Add("de", "battle_next_wave", "Naechste Welle in {0} Runden.");
            Add("de", "battle_bell_charged", "Nachziehglocke ist aufgeladen. Laeuten zieht kostenlos eine neue Hand.");
            Add("de", "battle_bell_charging", "Nachziehglocke ist in {0} Runden bereit. Jetzt laeuten verbraucht deinen Zug.");
            Add("de", "battle_bell_counter", "Aufgeladen in {0} Runden.");
            Add("de", "battle_phase_play", "Du bist dran.");
            Add("de", "battle_phase_other", "Warten.");
            Add("de", "battle_hit", "{0} trifft {1} fuer {2}.");
            Add("de", "battle_takes_damage", "{0} erleidet {1} Schaden.");
            Add("de", "battle_healed", "{0} heilt {1} Leben.");
            Add("de", "battle_dodged", "{0} ist ausgewichen.");
            Add("de", "battle_destroyed", "{0} zerstoert.");
            Add("de", "battle_status_applied", "{0} {1} auf {2} angewendet.");
            Add("de", "battle_your_unit", "dein {0}");
            Add("de", "battle_enemy_unit", "gegnerisches {0}");
            Add("de", "help_battle", "Kampf. Hoch und runter wechseln die Gruppen: Hand, dein Feld, Gegnerfeld, Glocke und Stapel. Links und rechts bewegen sich innerhalb einer Gruppe. Enter auf einer Handkarte nimmt sie auf; beim Halten wechseln hoch und runter die Reihe, links und rechts bewegen sich in der Reihe, nichts springt an den Anfang zurueck; Enter legt ab. Enter auf einer deiner Einheiten auf dem Feld nimmt sie zum Bewegen auf: ein freier Platz bewegt sie, ein besetzter Platz tauscht oder schiebt, die Rueckrufzone nimmt sie vom Feld. Bewegen und Zurueckrufen sind freie Aktionen und beenden deinen Zug nicht. Escape legt eine aufgenommene Karte zurueck. I untersucht die fokussierte Karte, Escape schliesst die Untersuchung. Eine Karte spielen oder die Glocke laeuten beendet deinen Zug. Vorlesetasten: H Hand, B Feld, W Wellen, R Glocke, T Runde, G Gold, M Modifikator-Glocken, Strg C Verbuendeten-Zaehler, Strg E Gegner-Zaehler, Strg H Verbuendeten-Leben, Strg Umschalt H Gegner-Leben. P oeffnet dein Inventar. O oeffnet das Spielmenue mit Einstellungen.");
            Add("de", "battle_unit_picked_up", "{0} vom Feld aufgenommen.");
            Add("de", "battle_move_hint", "Pfeiltasten waehlen einen Zielplatz oder die Rueckrufzone, Enter bestaetigt, Escape bricht ab.");
            Add("de", "tutorial_drag_hint", "Zum Auswaehlen und Ablegen: Enter auf der Karte druecken, das Ziel mit den Pfeiltasten waehlen, dann erneut Enter druecken.");
            Add("de", "tutorial_inspect_hint", "Du kannst auch Strg gedrueckt halten und Hoch druecken, um alle Details der ausgewaehlten Karte einzeln zu hoeren. Strg plus Links oder Rechts wechselt zu anderen Lesepuffern.");
            Add("de", "tutorial_counter_keys_hint", "Du musst die Zaehler nicht Karte fuer Karte verfolgen: Strg C nennt jede deiner Einheiten und in wie vielen Runden sie handelt, Strg E dasselbe fuer die Gegner.");
            Add("de", "tutorial_health_keys_hint", "Um zu erfahren, wen du zurueckholen solltest: Strg H nennt das Leben deiner Gefaehrten, Strg Umschalt H das der Gegner.");
            Add("de", "battle_unit_moved", "{0} bewegt.");
            Add("de", "battle_unit_recalled", "{0} zurueckgerufen.");
            Add("de", "battle_free_action", "Freie Aktion, dein Zug geht weiter.");
            Add("de", "battle_pickup_cancelled", "{0} zurueckgelegt.");
            Add("de", "battle_cannot_move", "Diese Einheit kann gerade nicht bewegt werden.");
            Add("de", "battle_recall_zone", "Rueckrufzone. Hier ablegen, um die Einheit zurueckzurufen.");
            Add("de", "battle_play_anchor", "Spielzone. Enter spielt die Karte ohne Ziel.");
            Add("de", "battle_trigger_snowed", "{0} ist eingeschneit und kann nicht handeln.");
            Add("de", "battle_trigger_nullified", "Die Aktion von {0} wurde verhindert.");
            Add("de", "battle_trigger_smackback", "{0} schlaegt gegen {1} zurueck!");
            Add("de", "battle_trigger_laststand", "{0} handelt mit letzter Kraft!");
            Add("de", "battle_trigger_chain", "{0} wird von {1} ausgeloest.");
            Add("de", "battle_trigger_acts", "{0} handelt.");
            Add("de", "battle_kill_combo", "Combo x{0}: {0} Abschuesse in diesem Zug.");
            Add("de", "battle_kill_combo_gold", "Combo x{0}: {0} Abschuesse in diesem Zug, {1} Bonusgold.");
            Add("de", "battle_gold_dropped", "{0} Gold.");
            Add("de", "battle_crown_deploy_one", "Eine gekroente Karte in deiner Hand wird vor dem Kampf eingesetzt: Enter darauf, um sie jetzt zu platzieren.");
            Add("de", "battle_crown_deploy", "{0} gekroente Karten in deiner Hand werden vor dem Kampf eingesetzt: platziere sie jetzt.");
            Add("de", "card_crowned", "Gekroent, wird bei Kampfbeginn eingesetzt.");
            Add("de", "card_charm_one", "Talisman: {0}.");
            Add("de", "card_charms", "{0} Talismane: {1}.");
            Add("de", "card_token_one", "Marke: {0}.");
            Add("de", "card_tokens", "{0} Marken: {1}.");
            Add("de", "counter_frozen", "Zaehler durch Schnee eingefroren");
            Add("de", "battle_status_damage", "{0} erleidet {1} {2}-Schaden.");
            Add("de", "battle_shell_blocked", "{0}: Shell blockt {1} Schaden.");
            Add("de", "battle_shell_blocked_all", "{2} trifft {0}. Shell blockt alle {1} Schaden.");
            Add("de", "battle_counter_reduced", "{0}: Zaehler um {1} gesenkt, handelt in {2}.");
            Add("de", "battle_attack_gain", "{0} erhaelt {1} Angriff, jetzt {2}.");
            Add("de", "battle_attack_lose", "{0} verliert {1} Angriff, jetzt {2}.");
            Add("de", "battle_counter_gain", "{0}: Zaehler um {1} erhoeht, handelt in {2}.");
            Add("de", "battle_counters_allies", "Verbuendeten-Zaehler");
            Add("de", "battle_counters_enemies", "Gegner-Zaehler");
            Add("de", "battle_counters_none_ally", "Keine Verbuendeten mit Zaehler.");
            Add("de", "battle_counters_none_enemy", "Keine Gegner mit Zaehler.");
            Add("de", "battle_health_allies", "Verbuendeten-Leben");
            Add("de", "battle_health_enemies", "Gegner-Leben");
            Add("de", "battle_health_none_ally", "Keine Verbuendeten auf dem Feld.");
            Add("de", "battle_health_none_enemy", "Keine Gegner auf dem Feld.");
            Add("de", "nav_edge", "Rand.");
            Add("de", "battle_not_a_target", "Kein gueltiges Ziel fuer diese Karte.");
            Add("de", "event_item_taken", "{0} genommen.");
            Add("de", "status_mech_applies", "gibt {0} {1}");
            Add("de", "status_mech_damage", "verursacht {0} Schaden");
            Add("de", "mech_when_card_destroyed", "wenn eine andere Karte zerstoert wird");
            Add("de", "mech_when_ally_killed", "wenn ein Verbuendeter getoetet wird");
            Add("de", "mech_when_unit_killed", "wenn eine Einheit getoetet wird");
            Add("de", "mech_when_clunker_destroyed", "wenn ein Clunker zerstoert wird");
            Add("de", "mech_when_hit", "wenn getroffen");
            Add("de", "mech_when_unit_hit", "wenn eine andere Einheit getroffen wird");
            Add("de", "mech_when_damage_taken", "wenn Schaden erlitten wird");
            Add("de", "mech_when_healed", "bei Heilung");
            Add("de", "mech_when_ally_healed", "wenn ein Verbuendeter geheilt wird");
            Add("de", "mech_when_deployed", "beim Einsetzen");
            Add("de", "mech_when_destroyed", "bei Zerstoerung");
            Add("de", "mech_when_drawn", "beim Ziehen");
            Add("de", "mech_on_kill", "nach einem Kill");
            Add("de", "mech_on_turn", "in seinem Zug");
            Add("de", "mech_every_turn", "jede Runde");
            Add("de", "mech_after_attack", "nach dem Angriff");
            Add("de", "mech_on_hit", "wenn es trifft");
            Add("de", "mech_to_self", "an sich selbst");
            Add("de", "mech_to_allies", "an alle Verbuendeten");
            Add("de", "mech_to_allies_row", "an Verbuendete in seiner Reihe");
            Add("de", "mech_to_front_ally", "an den vordersten Verbuendeten");
            Add("de", "mech_to_enemies", "an alle Gegner");
            Add("de", "mech_to_front_enemy", "an den vordersten Gegner");
            Add("de", "mech_to_attacker", "an den Angreifer");
            Add("de", "mech_to_target", "an sein Ziel");
            Add("de", "mech_to_random_ally", "an einen zufaelligen Verbuendeten");
            Add("de", "mech_to_random_enemy", "an einen zufaelligen Gegner");
            Add("de", "mech_to_hand", "an Karten auf der Hand");
            Add("de", "mech_summons", "Beschwoert {0}: {1}.");
            Add("de", "mech_summons_bare", "Beschwoert {0}.");
            Add("de", "mech_summon_counter", "handelt alle {0}");
            Add("de", "mech_trigger_meaning", "Ausloesen heisst: diese Karte greift sofort an, wenn das passiert, auf ihr eigenes Ziel, zusaetzlich zu ihrem normalen Zug. Ihr Zaehler wird nicht zurueckgesetzt, der Angriff ist also gratis.");
            Add("de", "mech_trigger_retaliate", "Wird diese Karte getroffen, schlaegt sie sofort gegen den Angreifer zurueck, zusaetzlich zu ihrem normalen Zug.");
            Add("de", "card_injured_one", "Verletzt.");
            Add("de", "card_injured", "Verletzt x{0}.");
            Add("de", "card_mentions", "Erwaehnt {0}");
            Add("de", "upgrade_charm", "Talisman");
            Add("de", "upgrade_crown", "Krone");
            Add("de", "upgrade_token", "Marke");
            Add("de", "battle_last_stand", "Letztes Gefecht! {0} weigert sich zu fallen. Der Kampf entscheidet sich per Wuerfelwurf. Enter wuerfelt.");
            Add("de", "battle_last_stand_generic", "Letztes Gefecht! Der Kampf entscheidet sich per Wuerfelwurf. Enter wuerfelt.");
            Add("de", "battle_last_stand_rolling", "Die Wuerfel rollen.");
            Add("de", "battle_last_stand_won", "Du gewinnst das letzte Gefecht!");
            Add("de", "battle_last_stand_lost", "Du verlierst das letzte Gefecht.");
            Add("de", "battle_companion_injured", "{0} wurde verletzt!");
            Add("de", "crown_holder_empty", "Kronenhalter, leer. Die Krone wurde genommen.");
            Add("de", "battle_bell_name", "Nachziehglocke");
            Add("de", "battle_wave_bell_name", "Wellenglocke");
            Add("de", "battle_wave_incoming", "{0} Gegner treffen in {1} Zuegen ein.");
            Add("de", "battle_wave_overflow", "{0} davon passen nicht auf das gegnerische Feld.");
            Add("de", "battle_wave_call_early", "Kann gelaeutet werden, um die Welle frueher zu rufen.");
            Add("de", "battle_wave_call_reward", "Belohnung fuer sofortiges Laeuten: {0} Gold.");
            Add("de", "battle_no_modifiers", "Keine Modifikator-Glocken aktiv.");
            Add("de", "battle_modifier_bell", "Modifikator-Glocke.");
            Add("de", "screen_pause", "Spielmenue.");
            Add("de", "pause_hint", "Hoch und runter bewegen sich durch die Seite, Enter aktiviert. Links und rechts wechseln die Tabs oder aendern den Wert einer Einstellung. T springt zu den Tabs, Escape geht zurueck. O schliesst das Menue.");
            Add("de", "pause_no_tabs", "Hier sind keine Tabs erreichbar. Escape geht zurueck.");
            Add("de", "pause_tab_named", "{0}, Tab. Enter zum Oeffnen.");
            Add("de", "pause_tab", "Tab. Enter zum Oeffnen.");
            Add("de", "pause_tab_opened", "{0} geoeffnet.");
            Add("de", "pause_closed", "Menue geschlossen.");
            Add("de", "pause_unavailable", "Das Menue ist gerade nicht verfuegbar.");
            Add("de", "setting_adjust_hint", "Links und rechts aendern den Wert.");
            Add("de", "setting_percent", "{0} Prozent");
            Add("de", "nav_nothing", "Hier gibt es nichts zu fokussieren.");
            Add("de", "row_not_interactive", "Dieser Eintrag ist nur lesbar.");
            Add("de", "pause_lore_page", "Geschichtenseite");
            Add("de", "pause_lore_locked", "gesperrt");
            Add("de", "pause_lore_new", "neu");
            Add("de", "pause_lore_open_hint", "Enter zum Vorlesen.");
            Add("de", "pause_lore_close_hint", "Escape schliesst die Seite.");
            Add("de", "pause_lore_closed", "Seite geschlossen.");
            Add("de", "stat_no_value", "keine");
            Add("de", "help_pause", "Spielmenue. Hoch und runter bewegen sich durch die Seitenelemente, Enter aktiviert. Links und rechts bewegen sich durch die Tabs oder aendern den Wert einer Einstellung. T springt zur Tab-Leiste. Escape geht eine Ebene zurueck, zum Beispiel aus einer Einstellungskategorie. Tab und Umschalt Tab gehen ebenfalls durch die Seite. O schliesst das Menue.");
            Add("de", "event_prompt_action", "Enter druecken.");
            Add("de", "event_crack", "Riss {0} von 4.");
            Add("de", "select_blocked", "Das kann gerade nicht gewaehlt werden.");
            Add("de", "select_blocked_reason", "Noch nicht moeglich. {0}");
            Add("de", "inspect_opened", "Untersuche {0}. Escape schliesst.");
            Add("de", "inspect_closed", "Untersuchung geschlossen.");
            Add("de", "nothing_to_inspect", "Hier gibt es nichts zu untersuchen.");
            Add("de", "help_panel_hint", "Pfeiltasten links und rechts waehlen eine Schaltflaeche, Enter drueckt sie, Escape geht zurueck.");
            Add("de", "help_panel_no_back", "Diese Abfrage braucht eine Antwort. Links und rechts waehlen, dann Enter.");
            // Town overlays, the tribe strings and the unlock buildings. Tribe
            // names themselves stay as they are — Snowdwellers, Shademancers and
            // Clunkmasters are proper nouns the game never translates either.
            Add("de", "building_back", "Zurueck.");
            Add("de", "building_closed", "Geschlossen.");
            Add("de", "building_overlay_hint", "Pfeiltasten wechseln zwischen den Bannern, Enter oeffnet eines, Escape verlaesst, I liest erneut.");
            Add("de", "challenge_hidden", "{0}, verborgene Herausforderung");
            Add("de", "challenge_stone", "Herausforderung");
            Add("de", "charselect_back", "Zurueck");
            Add("de", "charselect_leader_pos", "Anfuehrer {0} von {1}: {2}");
            Add("de", "charselect_pet_pos", "Haustier {0} von {1}: {2}");
            Add("de", "event_node_CampaignNodeCharmShop", "Zauber-Laden");
            Add("de", "event_node_CampaignNodeCopyItem", "Gegenstand kopieren");
            Add("de", "event_node_CampaignNodeCurseItems", "Verfluchte Gegenstaende");
            Add("de", "icebreaker_hint", "Pfeiltasten wechseln zwischen den Karten-Ereignissen, Enter liest vor, was eines bewirkt, Escape verlaesst, I liest die Zusammenfassung erneut.");
            Add("de", "icebreaker_unlock_intro", "Schliesse diese Herausforderung ab, um das naechste Karten-Ereignis freizuschalten:");
            Add("de", "icebreaker_unlocked", "{0} von {1} Karten-Ereignissen freigeschaltet: {2}.");
            Add("de", "icebreaker_unlocked_none", "Noch keines der {0} Karten-Ereignisse ist freigeschaltet.");
            Add("de", "overlay_browse", "{0} Elemente. Nutze die Pfeiltasten, um sie durchzugehen.");
            Add("de", "overlay_item", "{0}, {1} von {2}");
            Add("de", "overlay_position", "{0} von {1}");
            Add("de", "shrine_hint", "Hoch und runter wechseln zwischen offen und abgeschlossen, links und rechts blaettern.");
            Add("de", "shrine_none_completed", "Keine abgeschlossenen Herausforderungen.");
            Add("de", "shrine_none_incomplete", "Keine offenen Herausforderungen.");
            Add("de", "shrine_row_completed", "Abgeschlossene Herausforderungen");
            Add("de", "shrine_row_incomplete", "Offene Herausforderungen");
            Add("de", "shrine_summary", "{0} offen, {1} abgeschlossen.");
            Add("de", "tribe_banner", "Stammesbanner");
            Add("de", "tribe_desc_Basic", "Der Startstamm und der anfaengerfreundlichste. Sie frieren Gegner mit Frost und Schnee ein, sodass diese Zuege aussetzen, und steigern ihren Angriff mit Bonus.");
            Add("de", "tribe_desc_Clunk", "Tueftler, die mit Klunkern, schweren Schrott-Einheiten und Schrott kaempfen. Sie ueberwaeltigen den Gegner mit schierer Masse und Maschinerie.");
            Add("de", "tribe_desc_Magic", "Ein aggressiver Stamm mit hohem Risiko, aufgebaut auf Schatten und Wuerze. Sie stapeln temporaeren Angriff, um schnell und hart zuzuschlagen, aber ihre Einheiten sind zerbrechlich.");
            Add("de", "tribe_leaders", "Anfuehrer: {0}.");
            Add("de", "tribe_leaders_random", "Die Anfuehrer werden zufaellig erzeugt: du waehlst aus dreien, nachdem du diesen Stamm gewaehlt hast.");
            Add("de", "tribe_no_roster", "Fuer diesen Stamm sind keine Anfuehrer und kein Startdeck aufgefuehrt.");
            Add("de", "tribe_starting_deck", "Startdeck: {0}.");
            Add("de", "tribe_unlock_intro", "Schliesse diese Herausforderung ab, um den naechsten Stamm freizuschalten:");
            Add("de", "tribehall_hint", "Pfeiltasten wechseln zwischen den Stammesbannern, Enter oeffnet die Seite des fokussierten Stammes, Escape verlaesst, I liest die Zusammenfassung erneut.");
            Add("de", "tribehall_unlocked", "{0} von {1} Staemmen freigeschaltet: {2}.");
            Add("de", "tribehall_unlocked_none", "Noch keiner der {0} Staemme ist freigeschaltet.");
            Add("de", "tutorial_drag_hint_infront", "So geht das: druecke Enter auf der Karte, waehle mit den Pfeiltasten die Einheit, vor die sie soll, und druecke dann Enter — deine Karte nimmt diesen Platz ein und schiebt die Einheit nach hinten.");
            Add("de", "unlock_all_done", "Hier ist alles freigeschaltet.");
            Add("de", "unlock_detail_back", "Escape geht zurueck.");
            Add("de", "unlock_entry_locked", "{0} ist noch gesperrt.");
            Add("de", "unlock_next_intro", "Naechste Freischaltung:");
            Add("de", "unlock_slot_locked", "Gesperrter Platz");
            Add("de", "unlock_state_locked", "gesperrt");
            Add("de", "unlock_state_unlocked", "freigeschaltet");
            Add("de", "unlockhut_hint", "Pfeiltasten wechseln zwischen den Plaetzen, Escape verlaesst, I liest die Zusammenfassung erneut.");
            Add("de", "unlockhut_unlocked", "{0} von {1} freigeschaltet: {2}.");
            Add("de", "unlockhut_unlocked_none", "Noch keiner der {0} Plaetze ist offen.");

            Add("de", "help_panel_closed", "Geschlossen.");
            Add("de", "help_event", "Ereignis-Bildschirm. Ein Story-Ereignis auf deiner Reise; Titel und Text werden vorgelesen, sobald sie erscheinen. Pfeiltasten wechseln zwischen Elementen, Enter aktiviert. In einem Laden nennt jede Ware ihren Preis und ob du sie dir leisten kannst; druecke Enter darauf zum Kaufen und G, um deinen aktuellen Goldstand zu hoeren. I untersucht die fokussierte Karte, so wie Rechtsklick fuer sehende Spieler, Escape schliesst die Untersuchung. P oeffnet dein Inventar.");

        }
    }
}
