using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.Localization;
using UnityEngine.Localization.Settings;

namespace WildfrostAccessibility
{
    /// <summary>
    /// The Spanish half of the screen handler string table (Town, ContinueRun,
    /// Map, Battle and the shared item descriptions).
    /// </summary>
    public static partial class Loc
    {
        private static void RegisterHandlerStringsSpanish()
        {
            // ----- Spanish ------------------------------------------------------

            Add("es", "stat_health", "{0} de vida");
            Add("es", "stat_health_of_max", "{0} de {1} de vida");
            Add("es", "stat_attack", "{0} de ataque");
            Add("es", "stat_counter", "contador {0}");
            Add("es", "pocket_draw", "Mazo de robo, {0} cartas");
            Add("es", "pocket_draw_one", "Mazo de robo, 1 carta");
            Add("es", "pocket_discard", "Pila de descarte, {0} cartas");
            Add("es", "pocket_discard_one", "Pila de descarte, 1 carta");
            Add("es", "card_count_multiple", "{0}, {1} copias");
            Add("es", "no_item_focused", "Nada seleccionado.");
            Add("es", "no_info_available", "No hay informacion disponible.");
            Add("es", "gold_amount", "Oro: {0}.");
            Add("es", "shop_price", "Cuesta {0} de oro.");
            Add("es", "shop_price_afford", "Cuesta {0} de oro. Tienes {1}.");
            Add("es", "shop_price_cant_afford", "Cuesta {0} de oro. No puedes pagarlo; tienes {1}.");
            Add("es", "scene_CharacterSelect", "Seleccion de personaje.");
            Add("es", "scene_Cards", "Coleccion de cartas.");
            Add("es", "scene_Mods", "Mods.");
            Add("es", "scene_Credits", "Creditos.");
            Add("es", "scene_TownUnlocks", "Desbloqueos del pueblo.");
            Add("es", "scene_Event", "Evento.");
            Add("es", "scene_BossReward", "Recompensa de jefe.");
            Add("es", "scene_BattleWin", "Batalla ganada! Pantalla de victoria.");
            Add("es", "scene_CampaignEnd", "Fin del viaje.");
            Add("es", "campaignend_win", "Victoria!");
            Add("es", "campaignend_defeat", "Derrotado.");
            Add("es", "campaignend_vanquished", "Victoria total!");
            Add("es", "campaignend_time", "Tiempo");
            Add("es", "campaignend_battles", "Batallas ganadas");
            Add("es", "campaignend_blings", "Blings");
            Add("es", "campaignend_score", "Tu puntuacion: {0}.");
            Add("es", "campaignend_town_progress", "Progreso del pueblo: {0}.");
            Add("es", "help_campaignend", "Resumen al terminar un viaje: resultado, estadisticas de la partida, progreso del pueblo y puntuacion final. Las flechas llegan a Volver al pueblo y Puntuaciones, Enter selecciona. Ctrl+Arriba repite el resumen.");
            Add("es", "battlewin_continue", "Pulsa Enter para continuar.");
            Add("es", "battlewin_injuries", "Heridos en esta batalla: {0}.");
            Add("es", "battlewin_not_ready", "La pantalla de victoria todavia esta apareciendo, un momento.");
            Add("es", "help_battlewin", "Pantalla de victoria tras ganar una batalla. Puede mostrar companeros heridos en el combate. Enter continua el viaje.");
            Add("es", "charselect_leaders", "Elige a tu lider. Las flechas cambian de lider, Enter selecciona.");
            Add("es", "charselect_chosen", "{0} elegido. Enter confirma, Escape devuelve la carta.");
            Add("es", "charselect_chosen_generic", "Carta elegida. Enter confirma, Escape la devuelve.");
            Add("es", "charselect_cancelled", "Eleccion cancelada, de vuelta a la lista.");
            Add("es", "charselect_pets", "Elige tu mascota inicial. Las flechas cambian, Enter selecciona.");
            Add("es", "charselect_starting", "Vamos! Comienza el viaje.");
            Add("es", "tribe_locked", "{0}, bloqueada");
            Add("es", "tribe_locked_hint", "Las tribus nuevas se desbloquean segun se llena la barra de progreso del pueblo: sigue ganando batallas y terminando partidas.");
            Add("es", "tribe_locked_building", "El desbloqueo aparece en {0}.");
            Add("es", "tribe_locked_blocked", "{0} esta bloqueada, asi que no se puede elegir. {1}");
            Add("es", "charselect_tribes_locked", "Las tribus que aun no has desbloqueado se siguen mostrando: se leen como bloqueadas y no se pueden elegir.");
            Add("es", "inspect_no_confirm", "Este panel no se puede confirmar aqui. Escape devuelve la carta.");
            Add("es", "help_charselect", "Seleccion de personaje, en tres etapas. Primero una tribu: las flechas arriba y abajo cambian entre las tribus y leen el nombre y el estilo de cada una, la flecha derecha lee los lideres y el mazo inicial de la tribu, y Control mas arriba los recorre en el bufer de revision. Enter elige la tribu enfocada. Luego un lider y una mascota inicial, explorados con las flechas, Enter para elegir. Tras elegir una carta, Enter confirma y continua, Escape la devuelve. I inspecciona la carta enfocada.");
            Add("es", "help_main_menu", "Menu principal. Flechas arriba y abajo cambian de boton, Enter selecciona. F1 repite esta ayuda, F10 alterna el modo de depuracion.");
            Add("es", "screen_town", "Pueblo, tu campamento base.");
            Add("es", "town_hint", "Las flechas cambian de edificio, Enter selecciona, I describe el edificio seleccionado. F1 para ayuda.");
            Add("es", "gate_continue_tutorial", "Tu viaje de tutorial esta en curso. Pulsa Enter para continuarlo");
            Add("es", "gate_start_tutorial", "Comienza tu primer viaje. El juego te ofrecera el tutorial");
            Add("es", "gate_continue_run", "Tu viaje esta en curso. Pulsa Enter para continuarlo");
            Add("es", "gate_start_run", "Comienza un nuevo viaje");

            // Daily Voyage balloon
            Add("es", "balloon_start_run", "Comienza el viaje diario: un mazo fijo y modificadores, puntuado en la clasificacion. Enter abre el viaje de hoy");
            Add("es", "balloon_continue_run", "Tu viaje diario esta en curso. Pulsa Enter para continuarlo");
            Add("es", "balloon_deck", "Mazo fijo de {0} cartas: {1}");
            Add("es", "balloon_modifiers", "{0} modificadores: {1}");
            Add("es", "balloon_loading", "Viaje diario. Cargando el viaje de hoy.");
            Add("es", "balloon_play_desc", "Comienza el viaje diario de hoy");
            Add("es", "balloon_scores_desc", "Abre la clasificacion del viaje de hoy");
            Add("es", "balloon_buttons_hint", "Izquierda y derecha cambian entre Vamos y Clasificacion, Enter elige, I lo lee otra vez, Escape sale");
            Add("es", "help_town", "Pueblo. Tu base entre viajes. Los edificios desbloquean cartas y desafios. Las flechas cambian de edificio, I lee su funcion, Enter lo abre. La Puerta comienza o continua tu viaje.");
            Add("es", "screen_continue_run", "Continuar viaje. Tienes un viaje en curso.");
            Add("es", "continue_missing_data", "Este viaje usa contenido que falta y no puede continuarse.");
            Add("es", "continue_started", "Comenzado el {0}.");
            Add("es", "continue_leader", "Tu lider: {0}.");
            Add("es", "continue_deck", "Mazo de {0} cartas: {1}.");
            Add("es", "continue_hint", "Las flechas repasan cartas y botones. Enter en Vamos continua el viaje.");
            Add("es", "continue_button_desc", "Continua tu viaje");
            Add("es", "continue_back_desc", "Vuelve al pueblo");
            Add("es", "help_continue_run", "Pantalla de continuar viaje. Muestra el viaje en curso: lider, mazo y fecha de inicio. Enter en el boton de continuar reanuda el viaje. El boton de volver regresa al pueblo. Rendirse abandona el viaje.");
            Add("es", "screen_map", "Mapa del viaje.");
            Add("es", "map_zone", "Zona: {0}.");
            Add("es", "map_you_are_at", "Estas en {0}.");
            Add("es", "map_destinations", "{0} destinos: {1}.");
            Add("es", "map_hint", "Flechas izquierda y derecha recorren el camino, Enter viaja. M lee todo el mapa, I lee detalles, G lee el oro, P abre el inventario.");
            Add("es", "map_node_here", "estas aqui");
            Add("es", "map_node_enter", "Enter para entrar");
            Add("es", "map_only_location", "Este es el unico lugar revelado por ahora.");
            Add("es", "map_no_controls", "No hay nada mas en esta pantalla.");
            Add("es", "map_node_cleared", "completado");
            Add("es", "map_node_available", "disponible, pulsa Enter para viajar aqui");
            Add("es", "map_node_available_short", "disponible");
            Add("es", "map_node_ahead", "mas adelante");
            Add("es", "map_node_not_reachable", "no accesible");
            Add("es", "map_battle_waves", "{0} oleadas");
            Add("es", "map_not_ready", "El mapa aun no esta listo.");
            Add("es", "map_overview", "Resumen del mapa, {0} lugares conocidos.");
            Add("es", "map_hidden_nodes", "{0} lugares mas sin revelar");
            Add("es", "map_wave_enemies", "Oleada {0}: {1}");
            Add("es", "map_fork_here", "El camino se divide aqui y las ramas no vuelven a unirse: elegir una renuncia a las otras.");
            Add("es", "map_fork_rejoins", "las rutas vuelven a unirse, no se pierde nada");
            Add("es", "map_fork_gives_up", "elegir esto renuncia a: {0}");
            Add("es", "map_fork_gives_up_more", "elegir esto renuncia a: {0}, y {1} mas");
            Add("es", "map_fork_gives_up_unseen", "elegir esto renuncia a {0} lugares mas adelante en la otra rama");
            Add("es", "help_map", "Mapa del viaje. Tu viaje es un camino de lugares. Flechas izquierda y derecha cambian de lugar. Enter viaja a un lugar disponible. Arriba y abajo alcanzan los mazos y otros controles. M lee todo el mapa, I lee detalles del lugar seleccionado incluidos enemigos, G lee tu oro. P abre tu inventario con el mazo y los amuletos.");

            // Inventario (deckpack): mazo, reserva, amuletos, coronas
            Add("es", "deckpack_unavailable", "No hay inventario en esta pantalla.");
            Add("es", "deckpack_blocked", "El inventario no se puede abrir ahora.");
            Add("es", "deckpack_open", "Inventario abierto.");
            Add("es", "deckpack_closed", "Inventario cerrado.");
            Add("es", "deckpack_part_deck", "{0} en el mazo");
            Add("es", "deckpack_part_reserve", "{0} en la reserva");
            Add("es", "deckpack_part_charms", "{0} amuletos");
            Add("es", "deckpack_part_charm_one", "1 amuleto");
            Add("es", "deckpack_part_crowns", "{0} coronas");
            Add("es", "deckpack_part_crown_one", "1 corona");
            Add("es", "deckpack_hint", "Arriba y abajo cambian de grupo, izquierda y derecha se mueven dentro. Enter en un amuleto lo coge, Enter en una carta abre sus opciones. P o Escape cierra. F1 para la ayuda completa.");
            Add("es", "deckpack_group_deck", "Mazo, {0} cartas");
            Add("es", "deckpack_group_deck_one", "Mazo, 1 carta");
            Add("es", "deckpack_group_reserve", "Reserva, {0} cartas");
            Add("es", "deckpack_group_reserve_one", "Reserva, 1 carta");
            Add("es", "deckpack_group_charms", "Amuletos, {0}");
            Add("es", "deckpack_group_crowns", "Coronas, {0}");
            Add("es", "deckpack_group_controls", "Botones");
            Add("es", "deckpack_pickup", "{0} cogido. {1} cartas pueden llevarlo. Las flechas cambian entre ellas, Enter lo fija de forma permanente, Escape lo devuelve.");
            Add("es", "deckpack_pickup_one", "{0} cogido. Una carta puede llevarlo. Enter lo fija de forma permanente, Escape lo devuelve.");
            Add("es", "deckpack_pickup_none", "{0}: ninguna carta puede llevarlo ahora. Devuelto.");
            Add("es", "deckpack_battle_blocked", "Los amuletos no se pueden fijar durante la batalla.");
            Add("es", "deckpack_returned", "{0} devuelto.");
            Add("es", "deckpack_applying", "Fijando {0} a {1}.");
            Add("es", "deckpack_applied", "{0} fijado.");
            Add("es", "deckpack_not_eligible", "Esta carta no puede llevar {0}.");
            Add("es", "deckpack_target_slots", "{0} de {1} huecos de amuleto usados");
            Add("es", "charm_gained", "Amuleto conseguido! {0}");
            Add("es", "charm_gained_hint", "Enter lo fija ahora a una carta, Escape lo guarda en tu inventario para mas tarde.");
            Add("es", "charm_reserved", "{0} guardado en tu inventario. Fijalo cuando quieras pulsando P.");
            Add("es", "charm_assign_button", "{0} Enter fija este amuleto ahora a una carta, Escape lo guarda en tu inventario para mas tarde.");
            Add("es", "deckpack_menu_open", "Opciones de {0}: {1}. Izquierda y derecha eligen, Enter activa, Escape cierra.");
            Add("es", "deckpack_menu_closed", "Opciones cerradas.");
            Add("es", "deckpack_option_rename", "Renombrar");
            Add("es", "deckpack_option_take_crown", "Quitar corona");
            Add("es", "deckpack_option_move_reserve", "Mover a la reserva");
            Add("es", "deckpack_option_move_deck", "Mover al mazo");
            Add("es", "deckpack_moved_reserve", "{0} movida a la reserva.");
            Add("es", "deckpack_moved_deck", "{0} movida al mazo.");
            Add("es", "deckpack_crown_taken", "Corona quitada de {0} y devuelta al inventario.");
            Add("es", "deckpack_card_blocked", "Las opciones de carta no estan disponibles ahora.");
            Add("es", "help_deckpack", "Inventario. Tu mazo, cartas de reserva y los amuletos y coronas conseguidos. Arriba y abajo cambian de grupo: mazo, reserva, amuletos, coronas y botones. Izquierda y derecha se mueven dentro del grupo. Enter en un amuleto o corona lo coge: las flechas cambian entre las cartas que pueden llevarlo, Enter lo fija de forma permanente, Escape lo devuelve. Enter en una carta abre sus opciones, como moverla entre mazo y reserva. I inspecciona la carta enfocada. P o Escape cierra el inventario.");
            Add("es", "node_type_boss", "batalla de jefe");
            Add("es", "node_type_battle", "batalla");
            Add("es", "node_type_shop", "tienda");
            Add("es", "node_type_gnomeshop", "tienda de gnomos");
            Add("es", "node_type_charm", "evento de amuleto");
            Add("es", "node_type_gold", "tesoro");
            Add("es", "node_type_item", "evento de objeto");
            Add("es", "node_type_companion", "evento de companero");
            Add("es", "node_type_copyitem", "evento de copia de objeto");
            Add("es", "node_type_curseitems", "evento de maldicion");
            Add("es", "node_type_injuredcompanion", "companero herido");
            Add("es", "node_type_journalpage", "pagina del diario");
            Add("es", "node_type_charmshop", "tienda de amuletos");
            Add("es", "node_type_clunkshop", "tienda de trastos");
            Add("es", "node_type_muncher", "muncher");
            Add("es", "node_type_event", "evento");
            Add("es", "screen_battle", "Batalla!");
            Add("es", "battle_wave_total", "{0} oleadas enemigas.");
            Add("es", "battle_hand_count", "{0} cartas en mano.");
            Add("es", "battle_hint", "Arriba y abajo cambian entre mano, tableros, campana y pilas. Izquierda y derecha se mueven dentro. Enter coge y coloca cartas. F1 para ayuda de batalla.");
            Add("es", "battle_your_turn", "Tu turno. {0} cartas en mano.");
            Add("es", "battle_resolving", "Resolviendo el turno.");
            Add("es", "battle_over", "Batalla terminada.");
            Add("es", "battle_turn", "Turno {0}.");
            Add("es", "battle_bell_rung", "Campana de robo tocada. Robando una mano nueva.");
            Add("es", "battle_group_empty", "{0} esta vacio.");
            Add("es", "battle_nothing_to_focus", "Nada que seleccionar.");
            Add("es", "group_hand", "Mano");
            Add("es", "group_your_board", "Tu tablero");
            Add("es", "group_enemy_board", "Tablero enemigo");
            Add("es", "group_system", "Campana y pilas");
            Add("es", "battle_card_picked_up", "{0} en mano.");
            Add("es", "battle_pickup_hint", "Las flechas eligen objetivo, Enter la coloca.");
            Add("es", "battle_card_released", "{0} colocada.");
            Add("es", "battle_invalid_target", "Objetivo no valido.");
            Add("es", "battle_cannot_play", "No se puede jugar esa carta ahora.");
            Add("es", "battle_bell_not_ready", "La campana de robo no esta disponible ahora.");
            Add("es", "battle_hand_empty", "Tu mano esta vacia.");
            Add("es", "battle_acts_in", "actua en {0}");
            Add("es", "battle_use_on_hand", "Jugar sin objetivo");
            Add("es", "battle_no_waves", "Sin informacion de oleadas.");
            Add("es", "battle_wave_n", "Oleada {0}: {1}");
            Add("es", "battle_boss_wave", "oleada de jefe");
            Add("es", "battle_all_waves_spawned", "Todas las oleadas han aparecido.");
            Add("es", "battle_next_wave", "Proxima oleada en {0} turnos.");
            Add("es", "battle_bell_charged", "La campana de robo esta cargada. Tocarla roba una mano nueva gratis.");
            Add("es", "battle_bell_charging", "La campana de robo estara lista en {0} turnos. Tocarla ahora gasta tu turno.");
            Add("es", "battle_bell_counter", "Se carga en {0} turnos.");
            Add("es", "battle_phase_play", "Te toca.");
            Add("es", "battle_phase_other", "Esperando.");
            Add("es", "battle_hit", "{0} golpea a {1} por {2}.");
            Add("es", "battle_takes_damage", "{0} recibe {1} de dano.");
            Add("es", "battle_healed", "{0} recupera {1} de vida.");
            Add("es", "battle_dodged", "{0} esquivo el golpe.");
            Add("es", "battle_destroyed", "{0} destruido.");
            Add("es", "battle_status_applied", "{0} de {1} aplicado a {2}.");
            Add("es", "battle_your_unit", "tu {0}");
            Add("es", "battle_enemy_unit", "{0} enemigo");
            Add("es", "help_battle", "Batalla. Arriba y abajo cambian de grupo: mano, tu tablero, tablero enemigo, campana y pilas. Izquierda y derecha se mueven dentro del grupo. Enter en una carta de la mano la coge; mientras la sostienes, arriba y abajo cambian de fila, izquierda y derecha se mueven por la fila, nada da la vuelta; Enter la coloca. Enter en una de tus unidades del tablero la coge para moverla: una casilla libre la mueve, una ocupada intercambia o empuja, la zona de retirada la saca del tablero. Mover y retirar son acciones gratuitas que no terminan tu turno. Escape devuelve la carta cogida. I inspecciona la carta enfocada, Escape cierra la inspeccion. Jugar una carta o tocar la campana termina tu turno. Teclas de lectura: H mano, B tablero, W oleadas, R campana, T turno, G oro, M campanas de modificador, Control C contadores aliados, Control E contadores enemigos, Control H vida de los aliados, Control Mayus H vida de los enemigos. P abre tu inventario. Pulsa O para el menu del juego con los ajustes.");
            Add("es", "battle_unit_picked_up", "{0} levantada del tablero.");
            Add("es", "battle_move_hint", "Las flechas eligen una casilla de destino o la zona de retirada, Enter confirma, Escape cancela.");
            Add("es", "tutorial_drag_hint", "Para seleccionar y colocar: pulsa Enter sobre la carta, elige el destino con las flechas y pulsa Enter otra vez.");
            Add("es", "tutorial_inspect_hint", "Tambien puedes mantener Ctrl y pulsar arriba para recorrer todos los detalles de la carta seleccionada, uno por uno. Ctrl mas izquierda o derecha cambia a otros buferes de revision.");
            Add("es", "tutorial_counter_keys_hint", "No hace falta seguir los contadores carta por carta: pulsa Ctrl C para oir cada una de tus unidades y en cuantos turnos actua, y Ctrl E para lo mismo en el lado enemigo.");
            Add("es", "tutorial_health_keys_hint", "Para saber a quien conviene retirar, pulsa Ctrl H para la vida de tus companeros, o Ctrl Mayus H para la de los enemigos.");
            Add("es", "battle_unit_moved", "{0} movida.");
            Add("es", "battle_unit_recalled", "{0} retirada.");
            Add("es", "battle_free_action", "Accion gratuita, tu turno continua.");
            Add("es", "battle_pickup_cancelled", "{0} devuelta.");
            Add("es", "battle_cannot_move", "Esta unidad no se puede mover ahora.");
            Add("es", "battle_recall_zone", "Zona de retirada. Suelta aqui para retirar la unidad.");
            Add("es", "battle_play_anchor", "Zona de juego. Enter juega la carta sin objetivo.");
            Add("es", "battle_trigger_snowed", "{0} esta cubierta de nieve y no puede actuar.");
            Add("es", "battle_trigger_nullified", "La accion de {0} fue anulada.");
            Add("es", "battle_trigger_smackback", "{0} contraataca a {1}!");
            Add("es", "battle_trigger_laststand", "{0} actua con su ultimo aliento!");
            Add("es", "battle_trigger_chain", "{0} es activada por {1}.");
            Add("es", "battle_trigger_acts", "{0} actua.");
            Add("es", "battle_kill_combo", "Combo x{0}: {0} muertes este turno.");
            Add("es", "battle_kill_combo_gold", "Combo x{0}: {0} muertes este turno, {1} de oro extra.");
            Add("es", "battle_gold_dropped", "{0} de oro.");
            Add("es", "battle_crown_deploy_one", "Una carta coronada en tu mano se despliega antes de la batalla: pulsa Enter sobre ella para colocarla ahora.");
            Add("es", "battle_crown_deploy", "{0} cartas coronadas en tu mano se despliegan antes de la batalla: colocalas ahora.");
            Add("es", "card_crowned", "Coronada, se despliega al inicio de la batalla.");
            Add("es", "card_charm_one", "Amuleto: {0}.");
            Add("es", "card_charms", "{0} amuletos: {1}.");
            Add("es", "card_token_one", "Ficha: {0}.");
            Add("es", "card_tokens", "{0} fichas: {1}.");
            Add("es", "counter_frozen", "contador congelado por la nieve");
            Add("es", "battle_status_damage", "{0} recibe {1} de dano de {2}.");
            Add("es", "battle_shell_blocked", "{0}: Shell bloquea {1} de dano.");
            Add("es", "battle_shell_blocked_all", "{2} golpea a {0}. Shell bloquea los {1} de dano.");
            Add("es", "battle_counter_reduced", "{0}: contador reducido en {1}, actua en {2}.");
            Add("es", "battle_attack_gain", "{0} gana {1} de ataque, ahora {2}.");
            Add("es", "battle_attack_lose", "{0} pierde {1} de ataque, ahora {2}.");
            Add("es", "battle_counter_gain", "{0}: contador aumentado en {1}, actua en {2}.");
            Add("es", "battle_counters_allies", "Contadores aliados");
            Add("es", "battle_counters_enemies", "Contadores enemigos");
            Add("es", "battle_counters_none_ally", "Ningun aliado con contador.");
            Add("es", "battle_counters_none_enemy", "Ningun enemigo con contador.");
            Add("es", "battle_health_allies", "Vida de los aliados");
            Add("es", "battle_health_enemies", "Vida de los enemigos");
            Add("es", "battle_health_none_ally", "Ningun aliado en el tablero.");
            Add("es", "battle_health_none_enemy", "Ningun enemigo en el tablero.");
            Add("es", "nav_edge", "Borde.");
            Add("es", "battle_not_a_target", "No es un objetivo valido para esta carta.");
            Add("es", "event_item_taken", "Tomaste {0}.");
            Add("es", "status_mech_applies", "aplica {0} {1}");
            Add("es", "status_mech_damage", "causa {0} de dano");
            Add("es", "mech_when_card_destroyed", "cuando otra carta es destruida");
            Add("es", "mech_when_ally_killed", "cuando un aliado muere");
            Add("es", "mech_when_unit_killed", "cuando una unidad muere");
            Add("es", "mech_when_clunker_destroyed", "cuando un Clunker es destruido");
            Add("es", "mech_when_hit", "al ser golpeado");
            Add("es", "mech_when_unit_hit", "cuando otra unidad es golpeada");
            Add("es", "mech_when_damage_taken", "al recibir dano");
            Add("es", "mech_when_healed", "al ser curado");
            Add("es", "mech_when_ally_healed", "cuando un aliado es curado");
            Add("es", "mech_when_deployed", "al desplegarse");
            Add("es", "mech_when_destroyed", "al ser destruido");
            Add("es", "mech_when_drawn", "al robarse");
            Add("es", "mech_on_kill", "al matar");
            Add("es", "mech_on_turn", "en su turno");
            Add("es", "mech_every_turn", "cada turno");
            Add("es", "mech_after_attack", "despues de atacar");
            Add("es", "mech_on_hit", "al golpear");
            Add("es", "mech_to_self", "a si mismo");
            Add("es", "mech_to_allies", "a todos los aliados");
            Add("es", "mech_to_allies_row", "a los aliados de su fila");
            Add("es", "mech_to_front_ally", "al aliado delantero");
            Add("es", "mech_to_enemies", "a todos los enemigos");
            Add("es", "mech_to_front_enemy", "al enemigo delantero");
            Add("es", "mech_to_attacker", "al atacante");
            Add("es", "mech_to_target", "a su objetivo");
            Add("es", "mech_to_random_ally", "a un aliado al azar");
            Add("es", "mech_to_random_enemy", "a un enemigo al azar");
            Add("es", "mech_to_hand", "a las cartas de la mano");
            Add("es", "mech_summons", "Invoca a {0}: {1}.");
            Add("es", "mech_summons_bare", "Invoca a {0}.");
            Add("es", "mech_summon_counter", "actua cada {0}");
            Add("es", "mech_trigger_meaning", "Activarse significa que esta carta ataca en cuanto eso ocurre, a su propio objetivo, ademas de su turno normal. Su cuenta atras no se reinicia, asi que el ataque es gratis.");
            Add("es", "mech_trigger_retaliate", "Cuando algo golpea a esta carta, contraataca al agresor de inmediato, ademas de su turno normal.");
            Add("es", "card_injured_one", "Herido.");
            Add("es", "card_injured", "Herido x{0}.");
            Add("es", "card_mentions", "Menciona a {0}");
            Add("es", "upgrade_charm", "amuleto");
            Add("es", "upgrade_crown", "corona");
            Add("es", "upgrade_token", "ficha");
            Add("es", "battle_last_stand", "Ultimo aliento! {0} se niega a caer. La batalla se decide con una tirada de dados. Pulsa Enter para tirar los dados.");
            Add("es", "battle_last_stand_generic", "Ultimo aliento! La batalla se decide con una tirada de dados. Pulsa Enter para tirar los dados.");
            Add("es", "battle_last_stand_rolling", "Tirando los dados.");
            Add("es", "battle_last_stand_won", "Ganas el ultimo aliento!");
            Add("es", "battle_last_stand_lost", "Pierdes el ultimo aliento.");
            Add("es", "battle_companion_injured", "{0} ha sido herido!");
            Add("es", "crown_holder_empty", "Soporte de corona, vacio. La corona ya fue tomada.");
            Add("es", "battle_bell_name", "Campana de robo");
            Add("es", "battle_wave_bell_name", "Campana de oleadas");
            Add("es", "battle_wave_incoming", "{0} enemigos llegan en {1} turnos.");
            Add("es", "battle_wave_overflow", "{0} de ellos no cabran en el tablero enemigo.");
            Add("es", "battle_wave_call_early", "Puede tocarse para llamar la oleada antes.");
            Add("es", "battle_wave_call_reward", "Recompensa por tocarla ahora: {0} de oro.");
            Add("es", "battle_no_modifiers", "No hay campanas de modificador activas.");
            Add("es", "battle_modifier_bell", "Campana de modificador.");
            Add("es", "screen_pause", "Menu del juego.");
            Add("es", "pause_hint", "Arriba y abajo se mueven por la pagina, Enter activa. Izquierda y derecha cambian de pestana, o cambian el valor de un ajuste. T salta a las pestanas, Escape vuelve atras. Pulsa O para cerrar el menu.");
            Add("es", "pause_no_tabs", "No hay pestanas accesibles aqui. Escape vuelve atras.");
            Add("es", "pause_tab_named", "{0}, pestana. Enter para abrir.");
            Add("es", "pause_tab", "Pestana. Enter para abrir.");
            Add("es", "pause_tab_opened", "{0} abierta.");
            Add("es", "pause_closed", "Menu cerrado.");
            Add("es", "pause_unavailable", "El menu no esta disponible ahora.");
            Add("es", "setting_adjust_hint", "Izquierda y derecha cambian el valor.");
            Add("es", "setting_percent", "{0} por ciento");
            Add("es", "nav_nothing", "No hay nada que enfocar aqui.");
            Add("es", "row_not_interactive", "Esta entrada es de solo lectura.");
            Add("es", "pause_lore_page", "Pagina de historia");
            Add("es", "pause_lore_locked", "bloqueada");
            Add("es", "pause_lore_new", "nueva");
            Add("es", "pause_lore_open_hint", "Enter para leer.");
            Add("es", "pause_lore_close_hint", "Escape cierra la pagina.");
            Add("es", "pause_lore_closed", "Pagina cerrada.");
            Add("es", "stat_no_value", "ninguno");
            Add("es", "help_pause", "Menu del juego. Arriba y abajo se mueven por los elementos de la pagina, Enter activa. Izquierda y derecha se mueven por las pestanas, o cambian el valor de un ajuste. T salta a las pestanas. Escape vuelve un nivel atras, por ejemplo fuera de una categoria de ajustes. Tab y Mayus Tab tambien recorren la pagina. Pulsa O para cerrar el menu.");
            Add("es", "event_prompt_action", "Pulsa Enter.");
            Add("es", "event_crack", "Grieta {0} de 4.");
            Add("es", "select_blocked", "Esto no se puede elegir ahora mismo.");
            Add("es", "select_blocked_reason", "Aun no permitido. {0}");
            Add("es", "inspect_opened", "Inspeccionando {0}. Escape para cerrar.");
            Add("es", "inspect_closed", "Inspeccion cerrada.");
            Add("es", "nothing_to_inspect", "No hay nada que inspeccionar aqui.");
            Add("es", "help_panel_hint", "Las flechas izquierda y derecha eligen un boton, Enter lo pulsa, Escape vuelve atras.");
            Add("es", "help_panel_no_back", "Este aviso necesita una respuesta. Usa izquierda y derecha, luego Enter.");
            // Town overlays, the tribe strings and the unlock buildings. Tribe
            // names themselves stay as they are — Snowdwellers, Shademancers and
            // Clunkmasters are proper nouns the game never translates either.
            Add("es", "building_back", "Atras.");
            Add("es", "building_closed", "Cerrado.");
            Add("es", "building_overlay_hint", "Las flechas mueven entre los estandartes, Enter abre uno, Escape sale, I lee de nuevo.");
            Add("es", "challenge_hidden", "{0}, reto oculto");
            Add("es", "challenge_stone", "Reto");
            Add("es", "charselect_back", "Volver");
            Add("es", "charselect_leader_pos", "Lider {0} de {1}: {2}");
            Add("es", "charselect_pet_pos", "Mascota {0} de {1}: {2}");
            Add("es", "event_node_CampaignNodeCharmShop", "Tienda de amuletos");
            Add("es", "event_node_CampaignNodeCopyItem", "Copiar un objeto");
            Add("es", "event_node_CampaignNodeCurseItems", "Objetos malditos");
            Add("es", "icebreaker_hint", "Las flechas mueven entre los eventos de mapa, Enter lee que hace uno, Escape sale, I repite el resumen.");
            Add("es", "icebreaker_unlock_intro", "Completa este reto para desbloquear el siguiente evento de mapa:");
            Add("es", "icebreaker_unlocked", "{0} de {1} eventos de mapa desbloqueados: {2}.");
            Add("es", "icebreaker_unlocked_none", "Ninguno de sus {0} eventos de mapa esta desbloqueado todavia.");
            Add("es", "overlay_browse", "{0} elementos. Usa las flechas para recorrerlos.");
            Add("es", "overlay_item", "{0}, {1} de {2}");
            Add("es", "overlay_position", "{0} de {1}");
            Add("es", "shrine_hint", "Arriba y abajo cambian entre pendientes y completados, izquierda y derecha recorren.");
            Add("es", "shrine_none_completed", "No hay retos completados.");
            Add("es", "shrine_none_incomplete", "No hay retos pendientes.");
            Add("es", "shrine_row_completed", "Retos completados");
            Add("es", "shrine_row_incomplete", "Retos pendientes");
            Add("es", "shrine_summary", "{0} pendientes, {1} completados.");
            Add("es", "tribe_banner", "Estandarte de tribu");
            Add("es", "tribe_desc_Basic", "La tribu inicial y la mas apta para principiantes. Congelan a los enemigos con Escarcha y Nieve para que pierdan turnos, y aumentan su ataque con Bonus.");
            Add("es", "tribe_desc_Clunk", "Inventores que luchan con Chatarrunos, unidades pesadas de desguace, y Chatarra. Abruman al enemigo a base de masa y maquinaria.");
            Add("es", "tribe_desc_Magic", "Una tribu agresiva y de alto riesgo construida en torno a Sombra y Especia. Acumulan ataque temporal para golpear rapido y fuerte, pero sus unidades son fragiles.");
            Add("es", "tribe_leaders", "Lideres: {0}.");
            Add("es", "tribe_leaders_random", "Los lideres se generan al azar: eliges entre tres despues de escoger esta tribu.");
            Add("es", "tribe_no_roster", "Esta tribu no tiene lideres ni mazo inicial listados.");
            Add("es", "tribe_starting_deck", "Mazo inicial: {0}.");
            Add("es", "tribe_unlock_intro", "Completa este reto para desbloquear la siguiente tribu:");
            Add("es", "tribehall_hint", "Las flechas mueven entre los estandartes de tribu, Enter abre la pagina de la tribu enfocada, Escape sale, I repite el resumen.");
            Add("es", "tribehall_unlocked", "{0} de {1} tribus desbloqueadas: {2}.");
            Add("es", "tribehall_unlocked_none", "Ninguna de sus {0} tribus esta desbloqueada todavia.");
            Add("es", "tutorial_drag_hint_infront", "Como hacerlo: pulsa Enter sobre la carta, usa las flechas para elegir la unidad delante de la que quieres ponerla, y pulsa Enter — tu carta ocupa ese hueco y empuja a la unidad hacia atras.");
            Add("es", "unlock_all_done", "Aqui esta todo desbloqueado.");
            Add("es", "unlock_detail_back", "Escape vuelve atras.");
            Add("es", "unlock_entry_locked", "{0} sigue bloqueado.");
            Add("es", "unlock_next_intro", "Siguiente desbloqueo:");
            Add("es", "unlock_slot_locked", "Hueco bloqueado");
            Add("es", "unlock_state_locked", "bloqueado");
            Add("es", "unlock_state_unlocked", "desbloqueado");
            Add("es", "unlockhut_hint", "Las flechas mueven entre los huecos, Escape sale, I repite el resumen.");
            Add("es", "unlockhut_unlocked", "{0} de {1} desbloqueados: {2}.");
            Add("es", "unlockhut_unlocked_none", "Ninguno de sus {0} huecos esta abierto todavia.");

            Add("es", "help_panel_closed", "Cerrado.");
            Add("es", "help_event", "Pantalla de evento. Un evento de historia en tu viaje; su titulo y texto se leen cuando aparecen. Las flechas mueven entre elementos, Enter activa. En una tienda, cada articulo dice su precio y si puedes pagarlo; pulsa Enter sobre el para comprarlo, y G para oir tu oro actual. I inspecciona la carta enfocada, como el clic derecho para jugadores videntes, Escape cierra la inspeccion. P abre tu inventario.");

        }
    }
}
